### ISSUE TITLE
Lab Manager cannot create a new databox

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.databox#8]
Only Admin user is able to create a databox object in SENAITE

![Selection_019](https://user-images.githubusercontent.com/7425587/96027229-df865b00-0e57-11eb-9265-45baee78e641.png)

**Comment by ramonski** [comment]
Hey Pau,
this was finally fixed in https://github.com/senaite/senaite.databox/pull/24 ;)
Greetings, Ramon
